FROM jupyter/scipy-notebook:latest

RUN conda install -y -q nb_conda_kernels && \
    conda install -y -q -c anaconda netcdf4 && \
    conda install -y -q basemap &&  \
    conda install -y -q -c conda-forge cartopy && \
    conda install -y -q -c conda-forge pydap && \
    conda install -y -q -c conda-forge folium && \
    conda install -y -q -c conda-forge geopandas && \
    conda install -y -q -c conda-forge xarray